export const MUTATION_STATUS_GERMLINE = 'Germline';
export const AlterationTypeText = {
  MUTATION_EXTENDED: 'mutations',
  COPY_NUMBER_ALTERATION: 'copy number alterations',
  MRNA_EXPRESSION: 'mRNA expression',
  PROTEIN_LEVEL: 'protein expression',
  STRUCTURAL_VARIANT: 'structural variants',
  GENERIC_ASSAY: 'generic assay',
  GENESET_SCORE: 'geneset score',
  METHYLATION: 'methylation',
  MICRO_RNA_EXPRESSION: 'micro rna expression',
  MRNA_EXPRESSION_NORMALS: 'MRNA expression normals',
  METHYLATION_BINARY: 'methylation binary',
  MUTATION_UNCALLED: 'mutation uncalled',
  PHOSPHORYLATION: 'phosphorylation',
  PROTEIN_ARRAY_PHOSPHORYLATION: 'protein array phosphorylation',
  PROTEIN_ARRAY_PROTEIN_LEVEL: 'protein array protein level',
  RNA_EXPRESSION: 'RNA expression',
};

export const AlterationTypeConstants = {
  MUTATION_EXTENDED: 'MUTATION_EXTENDED',
  COPY_NUMBER_ALTERATION: 'COPY_NUMBER_ALTERATION',
  MRNA_EXPRESSION: 'MRNA_EXPRESSION',
  PROTEIN_LEVEL: 'PROTEIN_LEVEL',
  STRUCTURAL_VARIANT: 'STRUCTURAL_VARIANT',
  FUSION: 'FUSION',
  GENERIC_ASSAY: 'GENERIC_ASSAY',
  GENESET_SCORE: 'GENESET_SCORE',
  METHYLATION: 'METHYLATION',
  MICRO_RNA_EXPRESSION: 'MICRO_RNA_EXPRESSION',
  MRNA_EXPRESSION_NORMALS: 'MRNA_EXPRESSION_NORMALS',
  METHYLATION_BINARY: 'METHYLATION_BINARY',
  MUTATION_UNCALLED: 'MUTATION_UNCALLED',
  PHOSPHORYLATION: 'PHOSPHORYLATION',
  PROTEIN_ARRAY_PHOSPHORYLATION: 'PROTEIN_ARRAY_PHOSPHORYLATION',
  PROTEIN_ARRAY_PROTEIN_LEVEL: 'PROTEIN_ARRAY_PROTEIN_LEVEL',
  RNA_EXPRESSION: 'RNA_EXPRESSION',
};

export const PUTATIVE_DRIVER = 'Putative_Driver';
export const PUTATIVE_PASSENGER = 'Putative_Passenger';
